import type { components } from "./generated/schema";

// O OpenAPI tipa `ErrorBody.code` como string; a lista fechada vem do contrato
// (specs/001-auth, 003-contas-sociais, 004-kit-de-marca, 007, 006, 008, 014, 015, 016 e 017, contracts/http-api.md).
export const errorCodes = [
  "validation_error",
  "invalid_credentials",
  "email_not_verified",
  "email_in_use",
  "invalid_token",
  "unauthorized",
  "rate_limited",
  "internal_error",
  "forbidden",
  "password_change_required",
  "last_owner",
  "not_found",
  "conflict",
  "slug_in_use",
  "handle_in_use",
  "active_platform_exists",
  "version_conflict",
  "revert_conflict",
  "invalid_image",
  // 004-kit-de-marca
  "invalid_kit",
  "invalid_font",
  "font_name_in_use",
  "font_in_use",
  "invalid_video",
  "invalid_hook",
  "payload_too_large",
  "storage_unavailable",
  "storage_full",
  "perfil_archived",
  "not_ready",
  "invalid_link",
  // 007-assets-do-perfil
  "invalid_asset",
  "pose_label_in_use",
  "asset_in_use",
  "asset_archived",
  // 006-cortes-openshorts
  "invalid_channel_input",
  "canal_not_found",
  "canal_exists",
  "youtube_quota",
  "youtube_error",
  "youtube_unconfigured",
  "sync_running",
  "invalid_padroes",
  "already_selected",
  "already_sent",
  "video_unavailable",
  "invalid_url",
  "aviso_direito",
  "invalid_config",
  "postagem_exists",
  "corte_not_ready",
  "planned_in_past",
  "claude_unconfigured",
  "claude_error",
  "textos_timeout",
  "textos_invalidos",
  // 008-assistente-ia
  "invalid_ia",
  "ia_anteriores_invalidas",
  "ia_tipo_not_found",
  "ia_timeout",
  "ia_recusa",
  "ia_invalida",
  // 014-central-de-conteudos
  "conteudo_nao_pronto",
  "nao_aprovado",
  "aprovacao_necessaria",
  "modo_indisponivel",
  "conta_em_atencao",
  "conta_invalida",
  "destino_exists",
  "intervalo_conflito",
  "previa_desatualizada",
  // 015-tiktok-rascunho
  "somente_humano",
  "somente_dono",
  "publicacao_nao_configurada",
  "endereco_de_login",
  "state_invalido",
  "autorizacao_negada",
  "escopo_faltando",
  "conta_diferente",
  "conexao_em_uso",
  "identidade_indisponivel",
  "ja_conectada",
  "conta_nao_conectada",
  "precisa_reconectar",
  "rede_indisponivel",
  "tente_em_instantes",
  "opcoes_invalidas",
  "envio_em_andamento",
  "confirmacao_necessaria",
  "legenda_obrigatoria",
  "legenda_longa",
  // 016-metricas-tiktok
  "confirmar_anonimizacao",
  "video_ja_vinculado",
  "destino_ja_vinculado",
  "destino_sem_post",
  "sem_vinculo",
  "link_invalido",
  "link_outra_conta",
  "post_nao_encontrado",
  "metricas_indisponiveis",
  "periodo_invalido",
  // 017-guia-de-comunicacao
  "ia_proibida",
  // 009-mcp
  "nome_em_uso",
  "expira_no_passado",
  "mcp_cliente_revogado",
  "mcp_desligado",
  "mcp_suspenso",
  "mcp_origem",
  "escopo_mcp",
  "mcp_limite",
  "mcp_indisponivel",
  "alvo_arquivado",
  "proposta_so_em_destino",
  "campos_vazios",
  "nao_e_o_autor",
  "anotacao_fechada",
  "destino_aprovado",
  // 020-historico-tiktok-studio
  "arquivo_grande",
  "studio_arquivos",
  "studio_zip_inseguro",
  "studio_secao_nao_importada",
  "studio_formato",
  "studio_invalido",
  "studio_datas",
  "studio_conta_diferente",
  "serie_indisponivel",
  "confirmar_conta",
  "previa_indisponivel",
  "ja_desfeita",
  // 010-cenas
  "nao_encontrada",
  "arquivada",
  "cena_invalida",
  "cena_incompleta",
  "cena_usada",
  "cena_nao_pronta",
  "cena_rascunho",
  "cena_outro_perfil",
  "cena_arquivada",
  "origem_invalida",
  "proposta_invalida",
  "proposta_alvo_invalido",
  // 013-importacao
  "agencia_pasta_indisponivel",
  "agencia_pasta_grande",
  "importacao_em_andamento",
  "previa_expirada",
  "escolha_invalida",
  "importacao_nao_desfazivel",
] as const;

export type ErrorCode = (typeof errorCodes)[number];

export type ApiErrorBody = components["schemas"]["ErrorEnvelope"];

export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === "string" && (errorCodes as readonly string[]).includes(value);
}
